name: Deploy Supabase Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Supabase CLI
      run: npm install -g supabase

    - name: Login to Supabase
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      run: supabase login --token "${SUPABASE_ACCESS_TOKEN}"

    - name: Deploy Edge Function
      run: supabase functions deploy web-hook-stripe --project-ref "${{ secrets.SUPABASE_PROJECT_REF }}"
